let conatiner = document.querySelector(".container");

let sushiMenuData = [
  {
    id: 1,
    name: "Salmon Maki Sushi Roll",
    category: "Sushi Rolls",
    ingredients: "Rice, nori, salmon",
    piece: "6 pieces",
    kcal: 420,
    price: 9,
    salePercent: 0,
    img: "https://sushi24.ge/images/thumbs/0000765_syake-maki-11_510.jpeg",
  },
  {
    id: 2,
    name: "Philadelphia Special Sushi Roll",
    category: "Sushi Rolls",
    ingredients: "Rice, nori, cream cheese, avokado, smoked salmon",
    piece: "6 pieces",
    kcal: 420,
    price: 17,
    salePercent: 0,
    img: "https://sushi24.ge/images/thumbs/0000159_philadelphia-classic_510.png",
  },
  {
    id: 3,
    name: "California Ebi Sushi Roll",
    category: "Sushi Rolls",
    ingredients: "Rice, nori, cucumber, japanese mayonnaise, tobiko, shrimps.",
    piece: "6 pieces",
    kcal: 420,
    price: 15,
    salePercent: 0,
    img: "https://sushi24.ge/images/thumbs/0000688_california-rolls-with-salmon_510.png",
  },
  {
    id: 4,
    name: "Dragon Sushi Roll",
    category: "Sushi Rolls",
    ingredients: "Rice, nori, avokado, sesame, cream cheese, unagi fish",
    piece: "6 pieces",
    kcal: 420,
    price: 26,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/draqon-roll.jpg",
  },
  {
    id: 5,
    name: "Origami Sushi Roll",
    category: "Sushi Rolls",
    ingredients: "Rice, nori, chips, cream cheese, prawn tempura. ",
    piece: "6 pieces",
    kcal: 420,
    price: 10,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/oriqami-main.jpg",
  },
  {
    id: 6,
    name: "Canada Sushi Roll",
    category: "Sushi Rolls",
    ingredients: "Grilled salmon, salmon, cream cheese, avocado, rice, nori",
    piece: "6 pieces",
    kcal: 420,
    price: 18,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/canada-sushi-roll.jpg",
  },
  {
    id: 7,
    name: "Salmon Baked Sushi Roll",
    category: "Sushi Rolls",
    ingredients: "Rice, nori, salmon, baked sous.",
    piece: "6 pieces",
    kcal: 420,
    price: 13,
    salePercent: 0,
    img: "https://static.insales-cdn.com/images/products/1/273/197345553/365%D1%80%D0%BE%D0%BB%D0%BB_%D0%93%D0%BE%D1%80%D1%8F%D1%87%D0%B8%D0%B8%CC%86_%D1%81%D0%B0%D0%BC%D1%83%D1%80%D0%B0%D0%B8%CC%86.jpg",
  },
  {
    id: 8,
    name: "Chukka Sushi Roll",
    category: "Sushi Rolls",
    ingredients:
      "Rice, nori, cucumber, cream cheese, chukka algae and nut sauce, smoked salmon.",
    piece: "6 pieces",
    kcal: 420,
    price: 13,
    salePercent: 0,
    img: "https://img.freepik.com/premium-photo/sushi-set-close-up-isolated_109285-5085.jpg",
  },
  {
    id: 9,
    name: "Ebi nigiri",
    category: "Nigiri",
    ingredients: "Shimp, rice, wasabi",
    piece: "a piece",
    kcal: 220,
    price: 3,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/nigiri-ebi.jpg",
  },
  {
    id: 10,
    name: "Salmon nigiri",
    category: "Nigiri",
    ingredients: "Salmon, rice, wasabi.",
    piece: "a piece",
    kcal: 220,
    price: 4,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/salmon-nigiri-1.jpg",
  },
  {
    id: 11,
    name: "Unaqi nigiri",
    category: "Nigiri",
    ingredients: "Unagi, rice, wasabi",
    piece: "a piece",
    kcal: 220,
    price: 8,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/unaqi-nigiri.jpg",
  },
  {
    id: 12,
    name: "TOMAGO nigiri",
    category: "Nigiri",
    ingredients: "Tomago Omelette, Rice, Nori.",
    piece: "a piece",
    kcal: 220,
    price: 4,
    salePercent: 0,
    img: "https://sushi24.ge/images/thumbs/0000711_tomago-sushi_510.jpeg",
  },
  {
    id: 13,
    name: "Noodles Vegetable",
    category: "Noodles",
    ingredients: "Noodles udon, vegetables, sauces and spices",
    kcal: 380,
    piece: "",
    price: 8,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/noodles-vegetables-1.jpg",
  },
  {
    id: 14,
    name: "Noodles Chicken",
    category: "Noodles",
    ingredients: "Noodles udon, chicken fillet, vegetables, sauces and spices.",
    kcal: 380,
    piece: "",
    price: 10,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/noodles-chiken.jpg",
  },
  {
    id: 15,
    name: "Noodles Shrimp",
    category: "Noodles",
    ingredients: "Noodles udon, shrimps, vegetables, sauces and spices.",
    kcal: 380,
    piece: "",
    price: 15,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/noodles-shrimp.jpg",
  },
  {
    id: 16,
    name: "Noodles Salmon",
    category: "Noodles",
    ingredients: "Noodles udon, salmon fish, vegetables, sauces and spices.",
    kcal: 380,
    piece: "",
    price: 18,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/noodles-salmon.jpg",
  },
  {
    id: 17,
    name: "French fries",
    category: "Snacks",
    ingredients: "Potato",
    kcal: 460,
    piece: "",
    price: 4,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/800x800/frii.jpg",
  },
  {
    id: 18,
    name: "Nuggets",
    category: "Snacks",
    ingredients: "Chicken fillets, panko flakes",
    kcal: 460,
    piece: "",
    price: 7,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/800x800/naggets.jpg",
  },
  {
    id: 19,
    name: "Spring roll with chiken",
    category: "Snacks",
    ingredients: "Chiken fillets, vegetables, special sauce",
    kcal: 460,
    piece: "",
    price: 8,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/800x800/springedt.jpg",
  },
  {
    id: 20,
    name: "Calamary Tempura",
    category: "Snacks",
    ingredients: "Calamary rings, panco flakes",
    kcal: 460,
    piece: "",
    price: 8,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/800x800/kolca-kalmara-klare.jpg",
  },
  {
    id: 21,
    name: "Shrimp kebab",
    category: "Snacks",
    ingredients: "Shrimp, branded sauce",
    kcal: 460,
    piece: "",
    price: 14,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/800x800/krevetkabab1.jpg",
  },
  {
    id: 22,
    name: "Shrimp tempura",
    category: "Snacks",
    ingredients: "Tiger shrimp, panko",
    kcal: 460,
    piece: "",
    price: 14,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/800x800/krevetka.jpg",
  },

  {
    id: 23,
    name: "Mussels baked",
    category: "Snacks",
    ingredients: "Mussels, wine, baked cream sauce, lemon",
    kcal: 300,
    piece: "",
    price: 17,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/800x800/midye.jpg",
  },
  {
    id: 24,
    name: "Edamame",
    category: "Snacks",
    ingredients: "Edamame",
    kcal: 260,
    piece: "",
    price: 9,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/800x800/edamame-1.jpg",
  },
  {
    id: 25,
    name: "Tomato soup",
    category: "Soup",
    ingredients: "Parmesan cheese, tomatoes, cream",
    kcal: 240,
    piece: "",
    price: 5,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/800x800/tomato-soup7777.jpg",
  },
  {
    id: 26,
    name: "Miso Tofu",
    category: "Soup",
    ingredients: "Miso pasta, chondashi, vakama, sesame, tofu. ",
    kcal: 240,
    piece: "",
    price: 7,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/800x800/miso-tofu222.jpg",
  },

  {
    id: 27,
    name: "Miso salmon",
    category: "Soup",
    ingredients: "Miso pie, honeycomb, vakame, sesame, salmon, tofu cheese. ",
    kcal: 240,
    piece: "",
    price: 9,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/800x800/miso-salmon222.jpg",
  },
  {
    id: 28,
    name: "Tom Yam",
    category: "Soup",
    ingredients:
      "Tom yam pasta, coconut milk, shiitake mushrooms, shrimps, spices",
    kcal: 240,
    piece: "",
    price: 10,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/tom-yam666-1x1.jpg",
  },
  {
    id: 29,
    name: "Wasabi",
    category: "Sauce",
    ingredients: "300ml",
    piece: "",
    kcal: "",
    price: 1,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/800x800/wasabi.jpg",
  },
  {
    id: 30,
    name: "Soy sauce",
    category: "Sauce",
    ingredients: "300ml",
    piece: "",
    kcal: "",
    price: 1,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/800x800/soy-sauce.jpg",
  },
  {
    id: 31,
    name: "Ginger",
    category: "Sauce",
    ingredients: "300ml",
    piece: "",
    kcal: "",
    price: 1,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/800x800/ginger-1.jpg",
  },

  {
    id: 32,
    name: "Ketchup",
    category: "Sauce",
    ingredients: "300ml",
    piece: "",
    kcal: "",
    price: 1,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/800x800/ketchup-1.jpg",
  },
  {
    id: 33,
    name: "Mayonnaise",
    category: "Sauce",
    ingredients: "300ml",
    piece: "",
    kcal: "",
    price: 1,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/800x800/mayonnaise.jpg",
  },
  {
    id: 33,
    name: "Spicy",
    category: "Sauce",
    ingredients: "300ml",
    piece: "",
    kcal: "",
    price: 1,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/800x800/spicy.jpg",
  },
  {
    id: 34,
    name: "Cappy",
    category: "Drinks",
    ingredients: "200ml",
    piece: "",
    kcal: "",
    price: 2,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/800x800/cappy-multi.jpeg",
  },
  {
    id: 35,
    name: "Bonaqua",
    category: "Drinks",
    ingredients: "500ml",
    piece: "",
    kcal: "",
    price: 2,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/800x800/bonaquaqazsiz.jpg",
  },

  {
    id: 36,
    name: "Сoca Cola",
    category: "Drinks",
    ingredients: "330ml",
    piece: "",
    kcal: "",
    price: 3,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/800x800/coca-cola.jpg",
  },
  {
    id: 37,
    name: "Sprite",
    category: "Drinks",
    ingredients: "330ml",
    piece: "",
    kcal: "",
    price: 3,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/800x800/sprite-1.jpg",
  },
  {
    id: 38,
    name: "Fanta",
    category: "Drinks",
    ingredients: "330ml",
    piece: "",
    kcal: "",
    price: 3,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/800x800/fanta.jpg",
  },
  {
    id: 39,
    name: "Homemade Lemonad",
    category: "Drinks",
    ingredients: "330ml",
    piece: "",
    kcal: "",
    price: 6,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/800x800/lemonade.jpg",
  },
  {
    id: 40,
    name: "Tea Cup",
    category: "Drinks",
    ingredients: "200ml",
    piece: "",
    kcal: "",
    price: 3,
    salePercent: 0,
    img: "https://www.bakenroll.az/en/image/800x800/tea.jpg",
  },
];
// sushiMenuData.forEach((elem) => {
//   conatiner.innerHTML += `
//       <div>
//            <img src=${elem.img} alt="">
//            <h1>${elem.name}</h1>
//             <h4>${elem.piece ?? ""}</h4>
//             <h4>${elem.kcal + "kcal" ?? ""}</h4>
//            <h4>${elem.category}</h4>
//            <p>${elem.ingredients}</p>
//            <h3>${elem.price}</h3>
//         </div>
//     `;
// });
